program: scripts/phase2/ablations/optimize_att_no_fvp.py
method: bayes
metric:
  name: final_eval_acc
  goal: maximize
parameters:
  attention_act:
    values: ['Sigm', 'Tanh', 'ReLU']
  embed_dim:
    values: [ 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96, 102, 108, 114, 120, 126, 132, 138, 144, 150, 156, 162, 168, 174, 180, 186, 192, 198 ]
  out1:
    distribution: int_uniform
    min: 5
    max: 200
  out2:
    distribution: int_uniform
    min: 10
    max: 32
  out3:
    distribution: int_uniform
    min: 8
    max: 64
  dim_qk_gru:
    distribution: int_uniform
    min: 5
    max: 200
  dim_v:
    distribution: int_uniform
    min: 5
    max: 200
