program: scripts/phase2/att_comb/optimize_att_comb.py
method: bayes
metric:
    name: final_eval_acc
    goal: maximize
parameters:
    learning_rate1:
        distribution: log_uniform
        min: -12
        max: -2
    learning_rate2:
        distribution: log_uniform
        min: -12
        max: -2
    learning_rate3:
        distribution: log_uniform
        min: -12
        max: -2
    learning_rate_att:
        distribution: log_uniform
        min: -12
        max: -2
    gamma1:
        distribution: inv_log_uniform_values
        min: 0.5
        max: 1
    gamma2:
        distribution: inv_log_uniform_values
        min: 0.5
        max: 1
    gamma3:
        distribution: inv_log_uniform_values
        min: 0.5
        max: 1
    gamma_att:
        distribution: inv_log_uniform_values
        min: 0.5
        max: 1
    n_seq:
        values: [ 4, 8, 16, 32 ]
    num_epochs:
        values: [ 8, 10, 12, 14 ]
        
